name: file_dropzone_web
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      web:
        pluginClass: FileDropZone
        fileName: file_dropzone_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
